services:
  - type: web
    name: mspr63-back
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri-here
